### ISSUE TITLE
平板 安卓14  打开传输音频  屏幕镜像失败，关闭传输音频可以打开屏幕镜像 之前这个平板安卓13没问题升级14发生的问题

### ISSUE THREAD

**Issue by lengYueWuQing** [eiyooooo/Easycontrol_For_Car#67]
错误log如下:
<23:38:26> java.lang.IllegalStateException: setParameter() called on uninitialized AudioEffect.
	at android.media.audiofx.AudioEffect.checkState(AudioEffect.java:1444)
	at android.media.audiofx.AudioEffect.setParameter(AudioEffect.java:708)
	at android.media.audiofx.AudioEffect.setParameter(AudioEffect.java:722)
	at android.media.audiofx.LoudnessEnhancer.setTargetGain(LoudnessEnhancer.java:124)
	at t3.c.<init>(SourceFile:222)
	at t3.d.run(SourceFile:479)
	at java.lang.Thread.run(Thread.java:1012)

app_process -Djava.class.path=/data/local/tmp/easycontrol_for_car_server_10610.jar / top.eiyooooo.easycontrol.server.Scrcpy mirrorMode=1 keepAwake=0 ScreenMode=1000 useH265=0 useOpus=0 
alioth:/ $ app_process -Djava.class.path=/data/local/tmp/easycontrol_for_car_s
java.class.path=/data/local/tmp/easycontrol_for_car_s                         <erver_10610.jar / top.eiy
al/tmp/easycontrol_for_car_server_10610.jar / top.eiy                         <ooooo.easycontrol.server.
r_server_10610.jar / top.eiyooooo.easycontrol.server.                         <Scrcpy mirrorMode=1 keepA
eiyooooo.easycontrol.server.Scrcpy mirrorMode=1 keepA                         <wake=0 ScreenMode=1000 us
er.Scrcpy mirrorMode=1 keepAwake=0 ScreenMode=1000 us                         <eH265=0 useOpus=0 

DEBUG: <23:38:15> Construct Channel without a context
DEBUG: <23:38:15> Runnable run
DEBUG: <23:38:15> Context: top.eiyooooo.easycontrol.server.helper.FakeContext@96aa457
DEBUG: <23:38:15> PHONE_INFO->{"Build.MANUFACTURER":"Xiaomi","Build.MODEL":"M2012K11AC","Build.DEVICE":"alioth","Build.VERSION.RELEASE":"13","Build.VERSION.SDK_INT":33,"Build.BOARD":"alioth","Build.PRODUCT":"alioth","Build.USER":"builder","Build.BRAND":"Redmi","Build.HARDWARE":"qcom","Build.SUPPORTED_ABIS":"[arm64-v8a, armeabi-v7a, armeabi]"}
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at java.io.FileReader.<init>(FileReader.java:60)
	at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
	at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
	at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
	at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
	at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
	at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:40)
	at android.content.res.MiuiResources.<init>(MiuiResources.java:58)
	at android.content.res.IMiuiResourceImpl.createResources(IMiuiResourceImpl.java:13)
	at android.content.res.ThemeManagerStub.createMiuiResources(ThemeManagerStub.java:56)
	at android.content.res.Resources.getSystem(Resources.java:251)
	at android.app.LoadedApk.<init>(LoadedApk.java:253)
	at android.app.ContextImpl.createSystemContext(ContextImpl.java:3062)
	at android.app.ActivityThread.getSystemContext(ActivityThread.java:2865)
	at java.lang.reflect.Method.invoke(Native Method)
	at top.eiyooooo.easycontrol.server.utils.Workarounds.getSystemContext(Workarounds.java:178)
	at top.eiyooooo.easycontrol.server.helper.FakeContext.<init>(FakeContext.java:23)
	at top.eiyooooo.easycontrol.server.helper.FakeContext.<clinit>(FakeContext.java:16)
	at top.eiyooooo.easycontrol.server.helper.FakeContext.get(FakeContext.java:19)
	at top.eiyooooo.easycontrol.server.helper.AudioCapture.createAudioRecord(AudioCapture.java:46)
	at top.eiyooooo.easycontrol.server.helper.AudioCapture.init(AudioCapture.java:29)
	at top.eiyooooo.easycontrol.server.helper.AudioEncode.init(AudioEncode.java:31)
	at top.eiyooooo.easycontrol.server.Scrcpy.main(Scrcpy.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:368)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 27 more

<23:38:26> android.media.MediaCodec$CodecException: 
	at android.media.MediaCodec.native_start(Native Method)
	at android.media.MediaCodec.start(MediaCodec.java:2440)
	at o0.h.<init>(SourceFile:2)
	at t3.d.run(SourceFile:260)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by eiyooooo** [comment]
尝试关闭优先opus选项

**Comment by lengYueWuQing** [comment]
关闭优先opus选项 还是不行，也尝试了 优先H256 与 安卓14兼容模式 的开关 都不行。那可能联想 zui16 系统的问题。

> 尝试关闭优先opus选项

**Comment by eiyooooo** [comment]
> 关闭优先opus选项 还是不行，也尝试了 优先H256 与 安卓14兼容模式 的开关 都不行。那可能联想 zui16 系统的问题。
> 
> > 尝试关闭优先opus选项
> 
> 

也有可能和系统内的音效调节冲突了，可以试试关闭系统音效

**Comment by lengYueWuQing** [comment]
有个 杜比全景声 扬声器播放状态不能关闭，连接蓝牙关闭后 不行。

> > 关闭优先opus选项 还是不行，也尝试了 优先H256 与 安卓14兼容模式 的开关 都不行。那可能联想 zui16 系统的问题。
> > > 尝试关闭优先opus选项
> 
> 也有可能和系统内的音效调节冲突了，可以试试关闭系统音效

**Comment by eiyooooo** [comment]
> 有个 杜比全景声 扬声器播放状态不能关闭，连接蓝牙关闭后 不行。
> 
> > > 关闭优先opus选项 还是不行，也尝试了 优先H256 与 安卓14兼容模式 的开关 都不行。那可能联想 zui16 系统的问题。
> > > > 尝试关闭优先opus选项
> > 
> > 也有可能和系统内的音效调节冲突了，可以试试关闭系统音效
> 
> 

试试用scrcpy，看看能不能传音频

**Comment by lengYueWuQing** [comment]
联想的ZUI16（安卓14）的平板安装易控软件，让手机投屏到平板上。现在是平板从安卓13升级14，投屏声音出现问题（之前没问题），试过电脑运行scrcpy投屏这个联想平板或是之前被投屏的手机是可以的有声音。

> > 有个 杜比全景声 扬声器播放状态不能关闭，连接蓝牙关闭后 不行。
> > > > 关闭优先opus选项 还是不行，也尝试了 优先H256 与 安卓14兼容模式 的开关 都不行。那可能联想 zui16 系统的问题。
> > > > > 尝试关闭优先opus选项
> > > 
> > > 
> > > 也有可能和系统内的音效调节冲突了，可以试试关闭系统音效
> 
> 试试用scrcpy，看看能不能传音频

**Comment by eiyooooo** [comment]
> 联想的ZUI16（安卓14）的平板安装易控软件，让手机投屏到平板上。现在是平板从安卓13升级14，投屏声音出现问题（之前没问题），试过电脑运行scrcpy投屏这个联想平板或是之前被投屏的手机是可以的有声音。
> 
> > > 有个 杜比全景声 扬声器播放状态不能关闭，连接蓝牙关闭后 不行。
> > > > > 关闭优先opus选项 还是不行，也尝试了 优先H256 与 安卓14兼容模式 的开关 都不行。那可能联想 zui16 系统的问题。
> > > > > > 尝试关闭优先opus选项
> > > > 
> > > > 
> > > > 也有可能和系统内的音效调节冲突了，可以试试关闭系统音效
> > 
> > 试试用scrcpy，看看能不能传音频
> 
> 

尝试调整音频输出声道

**Comment by lengYueWuQing** [comment]
20个声道都试了，不行

> > 联想的ZUI16（安卓14）的平板安装易控软件，让手机投屏到平板上。现在是平板从安卓13升级14，投屏声音出现问题（之前没问题），试过电脑运行scrcpy投屏这个联想平板或是之前被投屏的手机是可以的有声音。
> > > > 有个 杜比全景声 扬声器播放状态不能关闭，连接蓝牙关闭后 不行。
> > > > > > 关闭优先opus选项 还是不行，也尝试了 优先H256 与 安卓14兼容模式 的开关 都不行。那可能联想 zui16 系统的问题。
> > > > > > > 尝试关闭优先opus选项
> > > > > 
> > > > > 
> > > > > 也有可能和系统内的音效调节冲突了，可以试试关闭系统音效
> > > 
> > > 
> > > 试试用scrcpy，看看能不能传音频
> 
> 尝试调整音频输出声道

**Comment by lengYueWuQing** [comment]
找到相同的问题链接，联想的问题，修改方法是异常捕获起来，尝试过不行，麻烦看下，还需要修改啥？
https://github.com/AntennaPod/AntennaPod/pull/7309

> 20个声道都试了，不行
> 
> > > 联想的ZUI16（安卓14）的平板安装易控软件，让手机投屏到平板上。现在是平板从安卓13升级14，投屏声音出现问题（之前没问题），试过电脑运行scrcpy投屏这个联想平板或是之前被投屏的手机是可以的有声音。
> > > > > 有个 杜比全景声 扬声器播放状态不能关闭，连接蓝牙关闭后 不行。
> > > > > > > 关闭优先opus选项 还是不行，也尝试了 优先H256 与 安卓14兼容模式 的开关 都不行。那可能联想 zui16 系统的问题。
> > > > > > > > 尝试关闭优先opus选项
> > > > > > 
> > > > > > 
> > > > > > 也有可能和系统内的音效调节冲突了，可以试试关闭系统音效
> > > > 
> > > > 
> > > > 试试用scrcpy，看看能不能传音频
> > 
> > 
> > 尝试调整音频输出声道

**Comment by lengYueWuQing** [comment]
找到相同的问题链接，联想的问题，修改方法是异常捕获起来，尝试过不行，有空麻烦看下，还需要修改啥？
https://github.com/AntennaPod/AntennaPod/pull/7309

> 找到相同的问题链接，联想的问题，修改方法是异常捕获起来，尝试过不行，麻烦看下，还需要修改啥？ [AntennaPod/AntennaPod#7309](https://github.com/AntennaPod/AntennaPod/pull/7309)
> 
> > 20个声道都试了，不行
> > > > 联想的ZUI16（安卓14）的平板安装易控软件，让手机投屏到平板上。现在是平板从安卓13升级14，投屏声音出现问题（之前没问题），试过电脑运行scrcpy投屏这个联想平板或是之前被投屏的手机是可以的有声音。
> > > > > > 有个 杜比全景声 扬声器播放状态不能关闭，连接蓝牙关闭后 不行。
> > > > > > > > 关闭优先opus选项 还是不行，也尝试了 优先H256 与 安卓14兼容模式 的开关 都不行。那可能联想 zui16 系统的问题。
> > > > > > > > > 尝试关闭优先opus选项
> > > > > > > 
> > > > > > > 
> > > > > > > 也有可能和系统内的音效调节冲突了，可以试试关闭系统音效
> > > > > 
> > > > > 
> > > > > 试试用scrcpy，看看能不能传音频
> > > 
> > > 
> > > 尝试调整音频输出声道

**Comment by eiyooooo** [comment]
> 找到相同的问题链接，联想的问题，修改方法是异常捕获起来，尝试过不行，有空麻烦看下，还需要修改啥？ [AntennaPod/AntennaPod#7309](https://github.com/AntennaPod/AntennaPod/pull/7309)

直接把

https://github.com/eiyooooo/Easycontrol_For_Car/blob/d7c50ed37fe3a16b9fec163c068c17bcab2ed534/easycontrol/app/src/main/java/top/eiyooooo/easycontrol/app/client/AudioDecode.java#L52

和

https://github.com/eiyooooo/Easycontrol_For_Car/blob/d7c50ed37fe3a16b9fec163c068c17bcab2ed534/easycontrol/app/src/main/java/top/eiyooooo/easycontrol/app/client/AudioDecode.java#L59

注释掉试试

**Comment by lengYueWuQing** [comment]
try
	{
      loudnessEnhancer = new LoudnessEnhancer(audioTrack.getAudioSessionId());
      loudnessEnhancer.setTargetGain(2000);
      loudnessEnhancer.setEnabled(true);

    }catch (Exception e){
      L.log("LoudnessEnhancer err", e);
    }
又调试下，发现捕获异常可以使用有声音了。 

> > 找到相同的问题链接，联想的问题，修改方法是异常捕获起来，尝试过不行，有空麻烦看下，还需要修改啥？ [AntennaPod/AntennaPod#7309](https://github.com/AntennaPod/AntennaPod/pull/7309)
> 
> 直接把
> 
> https://github.com/eiyooooo/Easycontrol_For_Car/blob/d7c50ed37fe3a16b9fec163c068c17bcab2ed534/easycontrol/app/src/main/java/top/eiyooooo/easycontrol/app/client/AudioDecode.java#L52
> 
> 和
> 
> https://github.com/eiyooooo/Easycontrol_For_Car/blob/d7c50ed37fe3a16b9fec163c068c17bcab2ed534/easycontrol/app/src/main/java/top/eiyooooo/easycontrol/app/client/AudioDecode.java#L59
> 
> 注释掉试试

**Comment by lengYueWuQing** [comment]
已解决
